# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e7aae114fb082a5d80d16dc7c46cace5ebf128eec97e2d652717dd4297070bdb4c44e507bffee79bccfa12d20f1a64d9a22a825be73e2c1d2a9d51caea282b

test:
  secret_key_base: c2be606fd34840daedf2c495e5f7ac75939319bb152339e6f524b97bc155cd1f0a6c450c12a36040e83ecd5eb2c6190d64a9a0123f79495bc495b71714624e98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
